name: Auto-Approve Pull Request

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read  # Permite ler o conteúdo do repositório
  actions: read   # Permite ler os logs e status das ações
  issues: write   # Permite comentar e fechar issues relacionadas a Pull Requests

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout no repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Instalar GitHub CLI
        run: sudo apt-get install -y gh

      - name: Aprovar o Pull Request automaticamente
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr list --state open --json number --jq '.[0].number')
          if [ -n "$PR_NUMBER" ]; then
            gh pr review "$PR_NUMBER" --approve
          else
            echo "Nenhum Pull Request aberto encontrado."
          fi