name: Auto-Merge Pull Request

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read
  actions: read
  issues: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar GitHub CLI
        run: sudo apt-get install -y gh

      - name: Mesclar o Pull Request automaticamente
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=$(gh pr list --state open --json number --jq '.[0].number')
          if [ -n "$PR_NUMBER" ]; then
            gh pr merge "$PR_NUMBER" --merge --admin --delete-branch
          else
            echo "Nenhum Pull Request aberto encontrado."
          fi
