name: Release

on:
  pull_request:
    types: [closed]  # Executa o workflow quando uma PR é fechada

jobs:
  release:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout no repository
      uses: actions/checkout@v3

    - name: Configurar Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.5

    - name: Install dependencies
      run: go mod download

    - name: Compilar o código
      run: go build -o nanogo ./cmd/nanogo

    - name: Configurar Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Versão Bump e push tag
      id: version
      uses: anothrNick/github-tag-action@v1.37.0
      with:
        tag_prefix: "v"
        release_branches: main
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Enviar o pacote para package do GitHub
      run: |
        go mod tidy
        go build -o nanogo ./cmd/nanogo
        GOPROXY=proxy.golang.org
        go publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
